config/routes.rb
Rails.application.routes.draw do
  resources :pcs
  resources :phones
  resources :cubes
  resources :hoges
  resources :games
  resources :books
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pc.rb
class Pc < ApplicationRecord
end

app/controllers/pcs_controller.rb
class PcsController < ApplicationController
  before_action :set_pc, only: [:show, :edit, :update, :destroy]

  # GET /pcs
  # GET /pcs.json
  def index
    @pcs = Pc.all
  end

  # GET /pcs/1
  # GET /pcs/1.json
  def show
  end

  # GET /pcs/new
  def new
    @pc = Pc.new
  end

  # GET /pcs/1/edit
  def edit
  end

  # POST /pcs
  # POST /pcs.json
  def create
    @pc = Pc.new(pc_params)

    respond_to do |format|
      if @pc.save
        format.html { redirect_to @pc, notice: 'Pc was successfully created.' }
        format.json { render :show, status: :created, location: @pc }
      else
        format.html { render :new }
        format.json { render json: @pc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pcs/1
  # PATCH/PUT /pcs/1.json
  def update
    respond_to do |format|
      if @pc.update(pc_params)
        format.html { redirect_to @pc, notice: 'Pc was successfully updated.' }
        format.json { render :show, status: :ok, location: @pc }
      else
        format.html { render :edit }
        format.json { render json: @pc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pcs/1
  # DELETE /pcs/1.json
  def destroy
    @pc.destroy
    respond_to do |format|
      format.html { redirect_to pcs_url, notice: 'Pc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pc
      @pc = Pc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pc_params
      params.require(:pc).permit(:name)
    end
end

app/helpers/pcs_helper.rb
module PcsHelper
end

app/views/pcs/_form.html.erb
<%= form_for(pc) do |f| %>
  <% if pc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pc.errors.count, "error") %> prohibited this pc from being saved:</h2>

      <ul>
      <% pc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pcs/edit.html.erb
<h1>Editing Pc</h1>

<%= render 'form', pc: @pc %>

<%= link_to 'Show', @pc %> |
<%= link_to 'Back', pcs_path %>

app/views/pcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pcs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pcs.each do |pc| %>
      <tr>
        <td><%= pc.name %></td>
        <td><%= link_to 'Show', pc %></td>
        <td><%= link_to 'Edit', edit_pc_path(pc) %></td>
        <td><%= link_to 'Destroy', pc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pc', new_pc_path %>

app/views/pcs/new.html.erb
<h1>New Pc</h1>

<%= render 'form', pc: @pc %>

<%= link_to 'Back', pcs_path %>

app/views/pcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pc.name %>
</p>

<%= link_to 'Edit', edit_pc_path(@pc) %> |
<%= link_to 'Back', pcs_path %>