config/routes.rb
Rails.application.routes.draw do
  resources :pcs
  resources :phones
  resources :cubes
  resources :hoges
  resources :games
  resources :books
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cube.rb
class Cube < ApplicationRecord
end

app/controllers/cubes_controller.rb
class CubesController < ApplicationController
  before_action :set_cube, only: [:show, :edit, :update, :destroy]

  # GET /cubes
  # GET /cubes.json
  def index
    @cubes = Cube.all
  end

  # GET /cubes/1
  # GET /cubes/1.json
  def show
  end

  # GET /cubes/new
  def new
    @cube = Cube.new
  end

  # GET /cubes/1/edit
  def edit
  end

  # POST /cubes
  # POST /cubes.json
  def create
    @cube = Cube.new(cube_params)

    respond_to do |format|
      if @cube.save
        format.html { redirect_to @cube, notice: 'Cube was successfully created.' }
        format.json { render :show, status: :created, location: @cube }
      else
        format.html { render :new }
        format.json { render json: @cube.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cubes/1
  # PATCH/PUT /cubes/1.json
  def update
    respond_to do |format|
      if @cube.update(cube_params)
        format.html { redirect_to @cube, notice: 'Cube was successfully updated.' }
        format.json { render :show, status: :ok, location: @cube }
      else
        format.html { render :edit }
        format.json { render json: @cube.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cubes/1
  # DELETE /cubes/1.json
  def destroy
    @cube.destroy
    respond_to do |format|
      format.html { redirect_to cubes_url, notice: 'Cube was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cube
      @cube = Cube.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cube_params
      params.require(:cube).permit(:name)
    end
end

app/helpers/cubes_helper.rb
module CubesHelper
end

app/views/cubes/_form.html.erb
<%= form_for(cube) do |f| %>
  <% if cube.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cube.errors.count, "error") %> prohibited this cube from being saved:</h2>

      <ul>
      <% cube.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cubes/edit.html.erb
<h1>Editing Cube</h1>

<%= render 'form', cube: @cube %>

<%= link_to 'Show', @cube %> |
<%= link_to 'Back', cubes_path %>

app/views/cubes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cubes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cubes.each do |cube| %>
      <tr>
        <td><%= cube.name %></td>
        <td><%= link_to 'Show', cube %></td>
        <td><%= link_to 'Edit', edit_cube_path(cube) %></td>
        <td><%= link_to 'Destroy', cube, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cube', new_cube_path %>

app/views/cubes/new.html.erb
<h1>New Cube</h1>

<%= render 'form', cube: @cube %>

<%= link_to 'Back', cubes_path %>

app/views/cubes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cube.name %>
</p>

<%= link_to 'Edit', edit_cube_path(@cube) %> |
<%= link_to 'Back', cubes_path %>